### ISSUE TITLE
My Request details

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#11]
For the People category, when a request is created, it does not show if the request is for Volunteer or Technical personnel, and it does not show quantity.

Content should be shown as follows:
   Type of people (Volunteer or Technical Personnel) (Qty)
   Item details
   Type of people (Volunteer or Technical Personnel) (Qty)
    Item details

The above should be visible on the "My Requests" page and the "Help requests received from" when view details is clicked.

**Comment by AvneeshGupta1** [comment]
fixed
