### ISSUE TITLE
Home screen Map -- Change address zoom

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#15]
On Home page map, when "Change" is clicked and a new address is entered/selected, the Map zooms out.  When you try to zoom back in, the App recalibrates the current location, and the new selected location is lost.

The ideal behavior should be.  Change and select address, the Map should do maximum zoom to that location so that the user can place the pin exactly based on local roads and neighbourhood.

**Comment by AvneeshGupta1** [comment]
fixed
