### ISSUE TITLE
Show system generated name to user

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#20]
### Expected behavior
As user enters their first name last name details, below those text boxes we show user the system generated name. 

Example:
For use Ramesh Sippy, show user R. Sippy. This would be the name/alias that would be used everywhere. 

### Screens
1. Screen 6, user registration.
2. Details of Requests.
3. Details of Offers.

![ShorthandProfileName](https://user-images.githubusercontent.com/451188/80802265-86d64500-8bcc-11ea-8dfb-db414ac96d4c.png)

**Comment by hellomitesh** [comment]
For users who represent an organization, the SystemName will be the name of the Organization (in full).  The Organization name will appear in Help-Seeker / Help-Giver.

**Comment by AvneeshGupta1** [comment]
fixed
