### ISSUE TITLE
Set default zoom of home screen map to one that shows the street

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#23]
Right now our logic of zoom on the map on home screen is related to numbers of markers visible. We have another open [issue](https://github.com/HelpinOutMovement/helpinout-app-android/issues/21) that would remove these markers altogether. Accordingly default zoom on home screen would be  maximum zoom that shows the streets.

**Comment by AvneeshGupta1** [comment]
fixed
