### ISSUE TITLE
"Ask for Help" should show option

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#24]
`Ask for Help` workflow needs to support the option of seeking help for person themselves or for other. On home screen, Screen 8, when user clicks on `Ask for Help` show dialogue with option of "Myself" and "Someone else".

![Ask for Help Options](https://user-images.githubusercontent.com/451188/80803137-0402b980-8bcf-11ea-88af-31e93c34124f.png)

**Comment by AvneeshGupta1** [comment]
done
