### ISSUE TITLE
Add new bubble on home screen for My Requests/Offers

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#25]
Whenever user receives a New Offer or New Request, on Home screen, Screen 8, we should show "New" Bubble for respective icons. 
![NewBubble](https://user-images.githubusercontent.com/451188/80803711-c2730e00-8bd0-11ea-85da-fe218b6d13a2.png)

**Comment by AvneeshGupta1** [comment]
We don't have any mechanism  to check request "My Request" or "My Offers" is viewed or not

**Comment by AvneeshGupta1** [comment]
fixed
