### ISSUE TITLE
Remove X for first row when user is Creating Request/Offer

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#27]
![Screenshot from 2020-05-01 17-32-36](https://user-images.githubusercontent.com/451188/80804119-d703d600-8bd1-11ea-82ba-d5a4e0c7f2e8.png)

**Comment by AvneeshGupta1** [comment]
This is invalid issue i don't see X in first row. or if you found this issue please give the steps to reproduce this

**Comment by baali** [comment]
I didn't notice this myself. It was part of the document shared with me. I will close this for now.
