### ISSUE TITLE
Add "Offer help to all", Bulk Outreach option

### ISSUE THREAD

**Issue by baali** [HelpinOutMovement/helpinout-app-android#29]
On Screen 18, when `Search for Help-Seekers` add option of “Offer help to all” check box so that an
organization and send offers to a large number of help-seekers.

![help-all](https://user-images.githubusercontent.com/451188/80804839-0287c000-8bd4-11ea-8bd1-e2cc5839c59f.png)

**Comment by AvneeshGupta1** [comment]
done
