### ISSUE TITLE
Rating/Ranking screen for Help-Seeker (Requester) and Help-Giver (Offeror)

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#37]
When a Help-Seeker (Requester) is rating a Help-Giver (Offeror) (Screen 26 in UI pdf), the text is:

**Should others take help from them?**

--------------------------------------------
When a Help-Giver (Offeror) is rating a Help-Seeker (Requester) (Screen 28 in UI pdf), the text is:

**Should others help them?**   

(right now it says "should others take help from them" -- this is incorrect)

**Comment by AvneeshGupta1** [comment]
fixed
