### ISSUE TITLE
Display of "Help request for someone else"

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#39]
I could not check if the Help requested "for someone else" is visible on the 
- Search for Help-Seeker map
- Sent offer to screen
- Request received from screen.

Can you please confirm.

**Comment by AvneeshGupta1** [comment]
This is not updated in design. Please update the ui where it should be displayed.

**Comment by AvneeshGupta1** [comment]
fixed
