### ISSUE TITLE
"New Matches" -- when it should appear and disappear

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#40]
NEW MATCHES are displayed on the following screens:
1. Home Screen:  Toggle "!"  "!"  
2. My Requests Screen  (bottom right of a request card)
3. My Offers Screen (bottom right of an offer card)

A New Match = a match that was identified after the user's last access of the "Search for Help Giver or Help Seeker" screens in the mobile app.

Therefore, the App keeps displaying "x" new matches until the user "searches" for the matches.   Once the user opens those pages, the back-end should identify that access time, and future new matches should be only those that occur after that time.  So, after the user accesses the Search for Help Giver or Help Seeker screens, the "New Matches" counter should be reset to 0 (zero).

**Comment by hellomitesh** [comment]
If New matches counter is "0", then do NOT show the toggles on Home Map, and do not show "New Matches" text on the Request and Offer cards.

**Comment by AvneeshGupta1** [comment]
Hi Mitesh if counter is 0 we are not showing "New Matches" and Toggle on Home Map. its coming from server.
