### ISSUE TITLE
Back arrow from Requests Sent to screen is incorrect

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#41]
Back arrow on top from "Requests sent to ..." screen should go back to MY REQUESTS.  

Currently, it goes back to "Seek help for... " page (where categories are selected).

Recreate these steps....
1. Create a new request.
2. Click yes to search for Help Giver (Provider)
3. Select Helps Givers
4. Goes to Requests sent to page
5.  Click back.... incorrectly goes to "Seek help for" screen.  It should go to My Requests screen.

Please check the same workflow for Offers

**Comment by AvneeshGupta1** [comment]
fixed
