### ISSUE TITLE
Bubble Alerts in Menu

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#43]
The Bubble Alerts (New) need to be changed to simple RED and Black dots (similar to the Red dot in the Menu).

Also, the New Bubble for My Offers does not disappear after viewing the "new request received"

**Comment by hellomitesh** [comment]
The First issue is solved.  The second issue -- the bubble on MY OFFERS keeps appearing, it does not disappear.

**Comment by AvneeshGupta1** [comment]
fixed
