### ISSUE TITLE
Report / Block text for Help Offer received from.... 

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#45]
The text should read "Should others take help from them?"

![Screenshot_2020-05-11-00-34-39-168_org helpinout billonlights](https://user-images.githubusercontent.com/63182057/81508127-d4b32180-931f-11ea-9f1e-c8154df66cfa.jpg)

**Comment by AvneeshGupta1** [comment]
fixed
