### ISSUE TITLE
Request / Offer Notifications and follow-up screen

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#47]
Issue 1:  If seeker / giver is from an organization, then the name in the Notification should be of the Organization.

Issue 2:  On clicking notification for help request, the App opened the "Help requests received from" screen (correct behavior), but it did not show the request for which the notification was received.  It showed "Your offer was registered, but no direct offer has been sent to anyone....".   

This behavior is incorrect, and is no longer relevant because the user cannot come to the 
"Offers sent to" /  "Requests sent to" / "Help requests received from" / "Help offers received from" screens UNTIL there is something to show on those pages.

**Comment by hellomitesh** [comment]
On another phone, received a "Request notification", then the same behavior as above.... it did not appear in the "Requests received from" screen.  It never shows up in the App.  even after exiting the app and opening it again.

**Comment by AvneeshGupta1** [comment]
Issue 1 done.
issue 2 unable to reproduce.
