### ISSUE TITLE
No loading indicator show when retrieving help providers after 'searching for help providers'

### ISSUE THREAD

**Issue by arunramanuj** [HelpinOutMovement/helpinout-app-android#5]
Under My Offers > (say) Food offer (rice kgs (30) placed on April 20, 6:28 pm > Search for Help providers > 

Takes some time to retrieve and show the help providers, but there is no loading indicator shown to indicate something is happening. The same thing should be taken care of when searching for requesters against an offer.

**Comment by AvneeshGupta1** [comment]
fixed
