### ISSUE TITLE
Distance shown in Select Help Seekers / Help Givers is incorrect

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#56]
The distance shown in Select Help Seekers / Help Givers should be the distance between the "Request" and the "Offer" that are being matched.  So if a Request was made in Nairobi (by a person sitting in India), and an Offer was made in Nairobi (by a person sitting in Tokyo), the distance between the Request and the Offer should be local -- within Nairobi.

**Comment by AvneeshGupta1** [comment]
Distance is coming from server and its fixed now
