### ISSUE TITLE
Asked to select a provider to send an offer, even though a provider was already selected

### ISSUE THREAD

**Issue by arunramanuj** [HelpinOutMovement/helpinout-app-android#6]
My Offers > Food offer (rice kgs (30) place on April 20, 6:28 pm > Search for Help providers >
Selected first requester Ved Chikarmane, Meals(2), 3 days ago - and clicked Send offer

First time I got a message ‘Please select at least one provider’, even though this one was selected.
Clicked second offer and clicked Send offer, then it worked.

Moved to home, came back to this screen, and clicked first offer, then it worked this time.

It should have worked the first time as well.

**Comment by AvneeshGupta1** [comment]
fixed
