### ISSUE TITLE
Details of Help Seekers content not visible

### ISSUE THREAD

**Issue by hellomitesh** [HelpinOutMovement/helpinout-app-android#64]
8097090069 was searching for Fruit & Veggies Help-Seeker.  

He found 8450999242 (Atmosys Support), but no details of the Help requested by Atmosys support was visible

![WhatsApp Image 2020-05-30 at 12 19 47 PM](https://user-images.githubusercontent.com/63182057/83321831-2e986e80-a270-11ea-9deb-4feb3b2a9d71.jpeg)

**Comment by AvneeshGupta1** [comment]
fixed

**Comment by hellomitesh** [comment]
Tested.  Fixed.
