### ISSUE TITLE
Cancelling an offer using the 'cancel' option on card should take one to the offer listing page

### ISSUE THREAD

**Issue by arunramanuj** [HelpinOutMovement/helpinout-app-android#7]
My offers -> Sent offers -> Cancelling an offer using the 'cancel' option on card cancels the offer, but keeps the user on the same screen (empty screen), but with a Cancel button at the bottom. Clicking the cancel button takes one to the sent offers listing with that offer cancelled.  Ideally, the first cancel itself should take one to the listing page.

**Comment by AvneeshGupta1** [comment]
fixed
